name: C++ CI

on:
  push:
      branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: make
        run: make
